# Generated by Django 2.1.7 on 2019-02-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'news'},
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.FileField(default=1, upload_to='news', verbose_name='image'),
            preserve_default=False,
        ),
    ]
