# Generated by Django 2.1.7 on 2019-02-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190224_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='announce_text',
            field=models.TextField(max_length=256, verbose_name='announce'),
        ),
    ]
