# Generated by Django 2.1.7 on 2019-02-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190225_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='approved'),
        ),
    ]
