# Generated by Django 2.1.7 on 2019-02-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190224_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='announce_text',
        ),
    ]
