# Generated by Django 2.1.7 on 2019-02-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_news_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('text', models.TextField(max_length=4096)),
                ('image', models.FileField(upload_to='locations')),
                ('cost', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='news',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(upload_to='news', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(max_length=4096, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Заголовок'),
        ),
    ]
