# Generated by Django 2.1.7 on 2019-02-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190225_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=64)),
                ('cost', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги',
            },
        ),
        migrations.CreateModel(
            name='BookingTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=64)),
                ('cost', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'тип бронирования',
                'verbose_name_plural': 'Типы бронирования',
            },
        ),
    ]
