# Generated by Django 2.1.7 on 2019-02-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_bookingoptions_bookingtypes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingoptions',
            options={'verbose_name': 'дополнительная услуга', 'verbose_name_plural': 'Бронирования / Дополнительные услуги'},
        ),
        migrations.AlterModelOptions(
            name='bookingtypes',
            options={'verbose_name': 'тип бронирования', 'verbose_name_plural': 'Бронирования / Типы бронирования'},
        ),
        migrations.AlterField(
            model_name='bookingoptions',
            name='desc',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='bookingtypes',
            name='desc',
            field=models.CharField(max_length=512),
        ),
    ]
