# Generated by Django 2.1.7 on 2019-02-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190225_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingoptions',
            options={'verbose_name': 'дополнительную услугу', 'verbose_name_plural': 'Бронирования / Дополнительные услуги'},
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={'verbose_name': 'локацию', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='photographs',
            options={'verbose_name': 'фотографа', 'verbose_name_plural': 'Фотографы'},
        ),
        migrations.AlterModelOptions(
            name='sarayuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'пользователя фотостудии', 'verbose_name_plural': 'Пользователи фотостудии'},
        ),
    ]
