# Generated by Django 2.1.7 on 2019-02-26 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190225_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='main.Locations')),
                ('options', models.ManyToManyField(blank=True, to='main.BookingOptions')),
                ('photograph', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='photograph', to='main.Photographs')),
                ('types', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='main.BookingTypes')),
            ],
            options={
                'verbose_name': 'бронирования',
                'verbose_name_plural': 'Бронирование',
            },
        ),
    ]
