# Generated by Django 2.1.7 on 2019-02-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='time_end',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='time_start',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
