# Generated by Django 2.1.7 on 2019-02-26 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190226_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='time_start',
        ),
    ]
