# Generated by Django 2.1.7 on 2019-02-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190226_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
