# Generated by Django 2.1.7 on 2019-02-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190226_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sarayuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'пользователя фотостудии', 'verbose_name_plural': 'Пользователя фотостудии'},
        ),
        migrations.AddField(
            model_name='sarayuser',
            name='insurance',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='СНИЛС'),
        ),
        migrations.AddField(
            model_name='sarayuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='bookingoptions',
            name='cost',
            field=models.SmallIntegerField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='bookingoptions',
            name='desc',
            field=models.CharField(max_length=512, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bookingoptions',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bookingtypes',
            name='cost',
            field=models.SmallIntegerField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='bookingtypes',
            name='desc',
            field=models.CharField(max_length=512, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bookingtypes',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='cost',
            field=models.SmallIntegerField(verbose_name='Стоимость аренды'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='image',
            field=models.FileField(upload_to='locations', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='text',
            field=models.TextField(max_length=4096, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Название локации'),
        ),
        migrations.AlterField(
            model_name='photographs',
            name='desc',
            field=models.CharField(max_length=64, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='photographs',
            name='first_name',
            field=models.CharField(max_length=32, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='photographs',
            name='image',
            field=models.FileField(upload_to='photographs', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='photographs',
            name='last_name',
            field=models.CharField(max_length=32, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='photographs',
            name='link',
            field=models.CharField(max_length=64, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='sarayuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='sarayuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='sarayuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Электропочта'),
        ),
        migrations.AlterField(
            model_name='sarayuser',
            name='fathersname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='sarayuser',
            name='firstname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='sarayuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный аккаунт'),
        ),
        migrations.AlterField(
            model_name='sarayuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Административный аккаунт'),
        ),
        migrations.AlterField(
            model_name='sarayuser',
            name='lastname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='sarayuser',
            name='passport_number',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='sarayuser',
            name='passport_series',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='sarayuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='sarayuser',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
