# Generated by Django 2.1.7 on 2019-02-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20190227_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='cost',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='payment_notification',
            field=models.BooleanField(default=False, verbose_name='Оповещение I'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='reminder_notification',
            field=models.BooleanField(default=False, verbose_name='Оповещение II'),
        ),
    ]
