# Generated by Django 2.1.7 on 2019-02-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20190227_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='status',
        ),
    ]
