# Generated by Django 2.1.7 on 2019-02-28 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_bookings_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'ordering': ['-status', '-date'], 'verbose_name': 'бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-approved', '-created_at'], 'verbose_name': 'новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='sarayuser',
            options={'ordering': ['is_superuser', 'is_staff', '-created_at'], 'verbose_name': 'пользователя фотостудии', 'verbose_name_plural': 'Пользователи фотостудии'},
        ),
        migrations.AddField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
