# Generated by Django 2.1.7 on 2019-02-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20190228_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarayuser',
            name='bonus',
            field=models.CharField(choices=[('CLASSIC', 'Классическая карта'), ('SILVER', 'Серебряная карта'), ('GOLD', 'Золотая карта'), ('PLATINUM', 'Платиновая карта')], default='CLASSIC', max_length=32, verbose_name='Бонусная карта'),
        ),
    ]
