# Generated by Django 2.1.7 on 2019-02-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_sarayuser_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManyFileField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='many', verbose_name='Множественные файлы')),
            ],
        ),
    ]
