# Generated by Django 2.1.7 on 2019-02-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_manyfilefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographs',
            name='files',
            field=models.ManyToManyField(blank=True, to='main.ManyFileField'),
        ),
    ]
