# Generated by Django 2.1.7 on 2019-02-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_photographs_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographs',
            name='files',
        ),
        migrations.DeleteModel(
            name='ManyFileField',
        ),
    ]
