# Generated by Django 2.1.7 on 2019-03-01 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20190228_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleImageNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='news', verbose_name='Изображение')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.News')),
            ],
        ),
    ]
