# Generated by Django 2.1.7 on 2019-03-01 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20190301_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleImageLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='locations', verbose_name='Изображение')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='main.Locations')),
            ],
            options={
                'verbose_name': 'фотографию студии',
                'verbose_name_plural': 'Фотографии студии',
            },
        ),
        migrations.AlterField(
            model_name='multipleimagephotographs',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='main.Photographs'),
        ),
    ]
