# Generated by Django 2.1.7 on 2019-03-01 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20190301_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleImageBookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_photos', models.FileField(upload_to='bookings/raw', verbose_name='RAW')),
                ('processed_photos', models.FileField(upload_to='bookings/processed', verbose_name='Ретушь')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.Bookings')),
            ],
            options={
                'verbose_name': 'фотографию',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
