# Generated by Django 2.1.7 on 2019-03-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_multipleimagebookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipleimagebookings',
            name='relation',
        ),
        migrations.DeleteModel(
            name='MultipleImageBookings',
        ),
    ]
