# Generated by Django 2.1.7 on 2019-03-01 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20190301_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleProcessedImageBookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='bookings/processed', verbose_name='Ретушь')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_processed', to='main.Bookings')),
            ],
            options={
                'verbose_name': 'ретушированную фотографию',
                'verbose_name_plural': 'Ретушированные фотографии',
            },
        ),
        migrations.CreateModel(
            name='MultipleRawImageBookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='bookings/raw', verbose_name='RAW')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_raw', to='main.Bookings')),
            ],
            options={
                'verbose_name': 'RAW-Фотографию',
                'verbose_name_plural': 'RAW-Фотографии',
            },
        ),
    ]
