# Generated by Django 2.1.7 on 2019-03-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_multipleprocessedimagebookings_multiplerawimagebookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarayuser',
            name='bonus_amount',
            field=models.SmallIntegerField(default=0, verbose_name='Бонусные баллы'),
        ),
    ]
