# Generated by Django 2.1.7 on 2019-03-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20190301_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographs',
            name='cost',
            field=models.SmallIntegerField(default=1000, verbose_name='Стоимость'),
        ),
    ]
