# Generated by Django 2.1.7 on 2019-03-04 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_photographs_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-approved', '-created_at'), 'verbose_name': 'новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='sarayuser',
            options={'ordering': ('is_superuser', 'is_staff', '-created_at'), 'verbose_name': 'пользователя фотостудии', 'verbose_name_plural': 'Пользователи фотостудии'},
        ),
        migrations.AlterField(
            model_name='bookings',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='main.Locations', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='options_choice', to='main.BookingOptions', verbose_name='Дополнительыне услуги'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='photograph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photograph', to='main.Photographs', verbose_name='Фотограф'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='time_start',
            field=models.TimeField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='types',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='main.BookingTypes', verbose_name='Тип бронирования'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='multipleimagelocations',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='main.Locations', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='multipleimagephotographs',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='main.Photographs', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='multipleprocessedimagebookings',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_processed', to='main.Bookings', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='multiplerawimagebookings',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_raw', to='main.Bookings', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
