# Generated by Django 2.1.7 on 2019-03-04 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20190304_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='time_end',
            field=models.TimeField(verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BookingTypes', verbose_name='Тип бронирования'),
        ),
    ]
