# Generated by Django 2.1.7 on 2019-03-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20190304_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='bonus_used',
            field=models.SmallIntegerField(default=0, verbose_name='Использованные бонусы'),
        ),
    ]
