# Generated by Django 2.1.7 on 2019-03-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_bookings_bonus_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='overcost',
            field=models.SmallIntegerField(default=0, verbose_name='Увеличенная стоимость аренды'),
        ),
        migrations.AlterField(
            model_name='bookingoptions',
            name='cost',
            field=models.SmallIntegerField(default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='cost',
            field=models.SmallIntegerField(default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='bookingtypes',
            name='cost',
            field=models.SmallIntegerField(default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='cost',
            field=models.SmallIntegerField(default=0, verbose_name='Стоимость аренды'),
        ),
        migrations.AlterField(
            model_name='photographs',
            name='cost',
            field=models.SmallIntegerField(default=0, verbose_name='Стоимость'),
        ),
    ]
