# Generated by Django 2.1.7 on 2019-03-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20190304_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='overcost',
        ),
        migrations.AddField(
            model_name='locations',
            name='over_time_cost',
            field=models.SmallIntegerField(default=0, verbose_name='Стоимость за время'),
        ),
        migrations.AddField(
            model_name='locations',
            name='over_week_cost',
            field=models.SmallIntegerField(default=0, verbose_name='Стоимость за день недели'),
        ),
    ]
