# Generated by Django 2.1.7 on 2019-03-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20190304_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sarayuser',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='options_choice', to='main.BookingOptions', verbose_name='Дополнительные услуги'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='over_time_cost',
            field=models.SmallIntegerField(default=0, verbose_name='Доп. стоимость (позднее время)'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='over_week_cost',
            field=models.SmallIntegerField(default=0, verbose_name='Доп. стоимость (дни недели)'),
        ),
    ]
