# Generated by Django 2.1.7 on 2019-03-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20190305_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sarayuser',
            old_name='fathersname',
            new_name='fathers_name',
        ),
        migrations.RenameField(
            model_name='sarayuser',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
