# Generated by Django 2.1.7 on 2019-03-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20190311_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarayuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='headshots', verbose_name='Изображение'),
        ),
    ]
